# Generated by Django 5.1.2 on 2024-11-07 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrigo', '0001_initial'),
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abrigo',
            name='voluntarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tste', to='voluntarios.voluntario', verbose_name='Voluntario'),
            preserve_default=False,
        ),
    ]
