# Generated by Django 5.1.2 on 2024-10-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrigo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abrigo',
            name='nome',
            field=models.CharField(default='nome padrao', max_length=255, verbose_name='Nome'),
        ),
    ]
