# Generated by Django 5.1.2 on 2024-11-07 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrigo', '0002_abrigo_voluntarios'),
        ('voluntarios', '0002_alter_voluntario_abrigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abrigo',
            name='voluntarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tste', to='voluntarios.voluntario', verbose_name='Voluntario'),
        ),
    ]
