# Generated by Django 5.1.2 on 2024-11-21 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrigo', '0003_alter_abrigo_voluntarios'),
        ('doacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abrigo',
            name='doacoes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teste', to='doacoes.doacao', verbose_name='Doacao'),
        ),
    ]
