# Generated by Django 5.1.2 on 2024-11-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abrigo', '0004_abrigo_doacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abrigo',
            name='doacoes',
        ),
    ]
