# Generated by Django 5.1.2 on 2024-11-21 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abrigo', '0006_alter_abrigo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abrigo',
            options={'permissions': (('Visualizar_Doacoes', 'Permite visualizar as doacoes'),), 'verbose_name': 'Abrigo', 'verbose_name_plural': 'Abrigos'},
        ),
    ]
