# Generated by Django 5.1.2 on 2024-10-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do voluntário', max_length=100, verbose_name='Nome')),
                ('idade', models.IntegerField(help_text='Idade do voluntário', verbose_name='Idade')),
                ('cpf', models.CharField(help_text='CPF do voluntário', max_length=11, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(help_text='Email do voluntário', max_length=254, verbose_name='Email')),
                ('endereco', models.CharField(help_text='Endereço do voluntário', max_length=200, verbose_name='Endereço')),
                ('quantidade', models.IntegerField(help_text='Quantidade associada ao voluntário', verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Voluntário',
                'verbose_name_plural': 'Voluntários',
            },
        ),
    ]
