# Generated by Django 5.1.2 on 2024-11-07 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrigo', '0002_abrigo_voluntarios'),
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='abrigo',
            field=models.ForeignKey(help_text='Nome do abrigo', on_delete=django.db.models.deletion.CASCADE, to='abrigo.abrigo', verbose_name=' Abrigo'),
        ),
    ]
