# Generated by Django 5.1.2 on 2024-10-31 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='quantidade',
        ),
    ]
