# Generated by Django 5.1.2 on 2024-10-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(help_text='Quantidade da doação', verbose_name='Quantidade')),
                ('unidade', models.IntegerField(help_text='Unidade de medida associada à doação', verbose_name='Unidade')),
                ('tipo', models.CharField(help_text='Tipo de item doado', max_length=100, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
            },
        ),
    ]
