# Generated by Django 5.1.2 on 2024-11-07 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abrigo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_doacao', models.CharField(help_text='Data em que a doação foi realizada', max_length=20, verbose_name='Data da Doação')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da doação', max_digits=10, verbose_name='Valor')),
                ('tipo_doacao', models.CharField(choices=[('MONETARIA', 'Monetária'), ('MATERIAL', 'Material'), ('SERVICO', 'Serviço')], help_text='Tipo de doação', max_length=20, verbose_name='Tipo de Doação')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('PROCESSANDO', 'Processando')], help_text='Status da doação', max_length=20, verbose_name='Status')),
                ('abrigo', models.ForeignKey(help_text='Nome do abrigo', on_delete=django.db.models.deletion.CASCADE, to='abrigo.abrigo', verbose_name='Abrigo')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
            },
        ),
    ]
