# Generated by Django 5.1.2 on 2024-11-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(help_text='Quantidade da doação', verbose_name='Quantidade')),
                ('unidade', models.IntegerField(help_text='Unidade de medida associada à doação', verbose_name='Unidade')),
                ('tipo', models.CharField(help_text='Tipo de item doado', max_length=100, verbose_name='Tipo de item')),
                ('data_doacao', models.DateField(help_text='Data em que a doação foi realizada', verbose_name='Data da Doação')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da doação', max_digits=10, verbose_name='Valor')),
                ('tipo_doacao', models.CharField(choices=[('MONETARIA', 'Monetária'), ('MATERIAL', 'Material'), ('SERVICO', 'Serviço')], help_text='Tipo de doação', max_length=20, verbose_name='Tipo de Doação')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('PROCESSANDO', 'Processando')], help_text='Status da doação', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
            },
        ),
    ]
