# Generated by Django 5.1.2 on 2024-11-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='unidade',
        ),
    ]
