# Generated by Django 5.1.2 on 2024-11-07 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0002_remove_doacao_tipo_remove_doacao_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='quantidade',
        ),
    ]
