# Generated by Django 5.1.2 on 2024-11-21 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrigo', '0004_abrigo_doacoes'),
        ('doacoes', '0002_alter_doacao_abrigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='abrigo',
            field=models.ForeignKey(help_text='Nome do abrigo', on_delete=django.db.models.deletion.CASCADE, related_name='doacoes_relacionadas', to='abrigo.abrigo', verbose_name=' Abrigo'),
        ),
    ]
