# Generated by Django 5.1.2 on 2024-11-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0003_remove_doacao_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='data_doacao',
            field=models.CharField(help_text='Data em que a doação foi realizada', max_length=20, verbose_name='Data da Doação'),
        ),
    ]
